### ISSUE TITLE
how to reference version?

### ISSUE THREAD

**Issue by blevonius** [mdsol/flask-mauth#8]
Hi @glow-mdsol ,

We have a project that depends on this. How can we reference a fixed version of this, ie not a branch? Tags?

**Comment by blevonius** [comment]
The master branch hasn't changed since Mar 3, 2017. Can we create a release/tag for this?

**Comment by glow-mdsol** [comment]
I think it's versioned in PyPI, but I will check

Geoff

Geoff Low Ph.D. |  Principal Innovation Scientist | Medidata Solutions

12 Hammersmith Grove, 9th Floor, Hammersmith, London, W6 7AP, UK.
glow@mdsol.com <emailaddress@mdsol.com> | direct: +44 (0) 208 6006504 |
main: +44 (0)208 7410333

**Comment by blevonius** [comment]
Yes it is, we'll use that, thanks.
